### ISSUE TITLE
Unclosed client session

### ISSUE THREAD

**Issue by s10ringleader** [GravelFire/CatsGangBot#4]
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001B607B82740>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001B607DEC8E0>, 2332981.562)]']
connector: <aiohttp.connector.TCPConnector object at 0x000001B607B82AA0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001B607B81930>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001B607DEC940>, 2332982.343)]']
connector: <aiohttp.connector.TCPConnector object at 0x000001B607B81BA0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001B607B83C70>
Unclosed connector

**Comment by oboroccv** [comment]
тоже самое
